name: Docker Build and Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t translate-app .

      # Run a test
      - name: Test Docker Container
        run: |
          docker run translate-app python translate.py --test "hello"
