name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repo
    - uses: actions/checkout@v4
    # Step 2: Build the docker container
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sidneysee/just-translate:latest
    # Step 3: Run the publish docker image script
    - name: Push Container
      run: docker push sidneysee/just-translate:latest